SELECT
	CODIGO,FH_NACIMIENTO,DATEDIFF(MONTH,FH_NACIMIENTO,GETDATE())/12.0 AS EDAD,
	CASE 
		WHEN DATEDIFF(MONTH,FH_NACIMIENTO,GETDATE())/12.0 <18 THEN '<18'
		WHEN DATEDIFF(MONTH,FH_NACIMIENTO,GETDATE())/12.0 <=25 THEN '18-25'
		WHEN DATEDIFF(MONTH,FH_NACIMIENTO,GETDATE())/12.0 <=35 THEN '26-35'
		WHEN DATEDIFF(MONTH,FH_NACIMIENTO,GETDATE())/12.0 <=40 THEN '36-40'
		WHEN DATEDIFF(MONTH,FH_NACIMIENTO,GETDATE())/12.0 <=50 THEN '41-50'
		WHEN DATEDIFF(MONTH,FH_NACIMIENTO,GETDATE())/12.0 <=65 THEN '51-65'
		ELSE '+65'
		
	END as 'RANGO EDAD'
	from TB_CLIENTE_PERFIL;

SELECT 
CODIGO,
SALDO_ACTIVO,
SALDO_PASIVO,
RENTABILIDAD,
SALDO_ACTIVO + SALDO_PASIVO AS VOLUMEN_NEGOCIO,
IIF((SALDO_ACTIVO + SALDO_PASIVO) = 0,
		0,
		RENTABILIDAD/(SALDO_ACTIVO + SALDO_PASIVO)) AS RATIO_RANTABILIDAD
FROM 
TB_CLIENTE_RENTABILIDAD;