select * from TB_CLIENTE_PERFIL;
 SELECT CODIGO, SEXO,FH_NACIMIENTO FROM TB_CLIENTE_PERFIL;
 select * from TB_CLIENTE_PERFIL WHERE SEXO='M';

 SELECT COUNT(DISTINCT(CODIGO)) as con_telefono from TB_CLIENTE_PERFIL where TIENE_TELEFONO ='S';

  select TOP 10 * from TB_CLIENTE_PERFIL order by INGRESO desc;

  SELECT TOP 20 PERCENT * FROM TB_CLIENTE_RENTABILIDAD ORDER BY RENTABILIDAD DESC;


SELECT * FROM TB_CLIENTE_RENTABILIDAD WHERE SALDO_PASIVO < 10000
  ORDER BY SALDO_PASIVO ASC;